import { Prisma } from "@prisma/client";

export const activeOnly: { delete_at: Date | null } = {
  delete_at: null,
};

export const DefaultSelectSO: Prisma.ppic_sap_sales_orderSelect = {
  DocNum: true,
  DocEntry: true,
  DocDate: true,
  DocDueDate: true,
  CreateDate: true,
  ReqDate: true,
  TaxDate: true,
  CardCode: true,
  CardName: true,
  Comments: true,
  U_MIS_approve1: true,
  U_MIS_approve2: true,
  U_MIS_approve3: true,
  U_MIS_SQFor: true,
  CANCELED: true,
  DocStatus: true,
  U_MIS_soreff: true,
  U_MIS_SOTYPE: true,
  BaseEntry: true,
  U_MIS_BruNet: true,
};

export const DefaultSelectSOLine: Prisma.ppic_sap_sales_order_docsSelect = {
  DocEntry: true,
  LineNum: true,
  BaseRef: true,
  BaseEntry: true,
  ItemCode: true,
  Dscription: true,
  LineStatus: true,
  Quantity: true,
  unitMsr: true,
  NumPerMsr: true,
  ShipDate: true,
  DocDate: true,
  GTotal: true,
  VatSum: true,
  VisOrder: true,
  U_MIS_labdipcode: true,
  U_MIS_labdipgroup: true,
  U_MIS_fabconst: true,
  U_MIS_yarnq: true,
  U_MIS_yarnc: true,
  U_MIS_spandex: true,
  U_MIS_ItemForeign: true,
  U_MIS_QtyOrder: true,
  U_MIS_UoMOrder: true,
  U_MIS_colour1: true,
  U_MIS_colour2: true,
  U_MIS_colour3: true,
  U_MIS_colour4: true,
  U_MIS_colour5: true,
  U_MIS_colour6: true,
  U_MIS_colour7: true,
  U_MIS_colour8: true,
  U_MIS_fabproc1: true,
  U_MIS_fabproc2: true,
  U_MIS_fabproc3: true,
  U_MIS_fabproc4: true,
  U_MIS_lineremarks: true,
  U_MIS_LabdipMaster: true,
  ppic_sap_sales_order: {
    select: {
      DocNum: true,
      U_MIS_soreff: true,
      U_MIS_SOTYPE: true
    },
  },
};
